### ISSUE TITLE
pretty-formula license

### ISSUE THREAD

**Issue by mzur** [preipke/OMPetri#2]
Hi, it's nice to see pretty-formula in use. Could you please include the [license](https://github.com/mzur/pretty-formula/blob/66962779120f0cceed65b983b5554b611e932d1f/LICENSE.txt) as well (as is required)? Thanks!

**Comment by mzur** [comment]
Hi again, I still can't find the license of pretty-formula in your repo. Please include it.

**Comment by preipke** [comment]
Hi, sorry, I am not an expert when it comes to licensing. I'm using the MIT license, as required from your original license (that I found in your repo). What else must be changed? The sources were originally handed to me from Christoph Brinkrolf directly, without any license in there.

**Comment by mzur** [comment]
Just put the [`LICENSE.txt`](https://github.com/mzur/pretty-formula/blob/66962779120f0cceed65b983b5554b611e932d1f/LICENSE.txt) of pretty-formula to some [appropriate location](https://github.com/preipke/OMPetri/tree/78770053445693e3e3cf27a19830bc1394f10311/PrettyFormula/src/main/java/edu/unibi/agbi/prettyformulafx) in your repository and you're fine 😉 This is independent from the actual license you choose for your own code.

**Comment by preipke** [comment]
How about now? Stored it in the PrettyFormula top directory. ;)

**Comment by mzur** [comment]
Alright, thanks!
